name: tars

volumes:
  db-data:
  pgadmin-data:

services:
  app:
    image: oven/bun:1.2
    restart: unless-stopped
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --inspect
    env_file: .env
    working_dir: /app
    entrypoint:
      - /bin/bash
      - -euxo
      - pipefail
      - -c
      - bun install && bun run db:migrate && bun run dev
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      

  db:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:8.14
    ports:
      - '5000:5000'
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@kvd.studio
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
    volumes:
      - pgadmin-data:/pgadmin
